chatrooms/urls.py
from django.urls import path, include
from .views import auth,system, user,connect,block,message,room

from django.contrib import admin

urlpatterns = [
    path('login', auth.Login.as_view(), name='li'),
    path('logout', auth.Logout.as_view(), name='lo'),

    path('config', system.ConfigView.as_view(), name='cf'),
    path('notice', system.NoticeListView.as_view(), name='nl'),



    path('user/list', user.UserListView.as_view(), name='ul'),
    path('user/search/<p>', user.UserSearchView.as_view(), name='us'),
    path('user/<int:pk>', user.UserDetailView.as_view(), name='ud'),
    path('user/create', user.UserCreateView.as_view(), name='uc'),
    path('user/<int:pk>/update', user.UserUpdateView.as_view(), name='uu'),
    path('user/<int:pk>/delete', user.UserDeleteView.as_view(), name='udl'),
    path('mypage', user.Mypage.as_view(), name='mp'),
    path('blocklist',block.BlockListView.as_view(), name='bl'),
    path('user/<int:pk>/block', block.BlockCreateView.as_view(), name='bc'),
    path('user/<int:pk>/blockend', block.BlockDeleteView.as_view(), name='bd'),
    path('user/<int:pk>/follow',connect.FollowListView.as_view(), name='fl1'),
    path('user/<int:pk>/follower',connect.FollowerListView.as_view(), name='fl2'),
    path('user/<int:pk>/connect',connect.ConnectCreateView.as_view(), name='cc'),
    path('user/<int:pk>/disconnect',connect.ConnectDeleteView.as_view(), name='cd'),
    path('messagebox',message.MessageBoxView.as_view(), name="mb"),
    path('message/<p>',message.MessageRoomView.as_view(), name="mr"),
    path('message/create/<p>',message.MessageCreate.as_view(), name="mc"),
    path('message/ajax',message.ajax, name="majax"),


    path('room/list', room.RoomListView.as_view(), name='rl'),
    path('room/<int:pk>/', room.RoomDetailView.as_view(), name='rd'),
    path('room/create', room.RoomCreateView.as_view(), name='rc'),
    path('room/<int:pk>/update', room.RoomUpdateView.as_view(), name='ru'),
    path('room/<int:pk>/delete', room.RoomDeleteView.as_view(), name='rdl'),

    path('room/<int:pk>/komento', room.PostCreate.as_view(), name='pc'),#ok

    path('dev', system.DevelopmentView.as_view(), name='dev'),
    path('dev/search', system.NavSearch.as_view(), name='ds'),
    path('', room.RoomListView.as_view(), name='index'),
]

chatroomsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('chatrooms.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chatrooms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    user_name = models.CharField(max_length=100, default="no name")
    memo = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    icon = models.ImageField(upload_to='icon', height_field=None, width_field=None, blank=True, max_length=100, default=False)
    icon_changed = models.DateTimeField(blank=True, auto_now=True)
    def __str__(self):
        return self.user_name
    
    REQUIRED_FIELDS = ["user_name","memo"]
    groups = None
    user_permissions = None
    last_login = None
    #superuser_status = False
    first_name = None
    last_name = None
    email_address = models.EmailField(default='notset@example.com')
    #staff_status = False
    date_joined = None

class Config(models.Model):
    open_config = [
        (0,'全体に公開する'),
        (1,'フレンドのみ公開'),
        (2,'非公開')
    ]
    receive_config = [
        (0,'全員に許可する'),
        (1,'フレンドのみ許可'),
        (2,'全員から受け取らない')
    ]

    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    darkmode = models.BooleanField(default=False,blank=False)
    room_post_log = models.IntegerField(choices=open_config, default=0)
    friend = models.IntegerField(choices=open_config, default=0)
    notice = models.IntegerField(choices=receive_config, default=0)
    message = models.IntegerField(choices=receive_config, default=0)

class Message(models.Model):
    sent = models.ForeignKey(CustomUser, related_name='sent_message', on_delete=models.CASCADE)
    received = models.ForeignKey(CustomUser, related_name='received_message', on_delete=models.CASCADE)
    text = models.TextField()
    image = models.ImageField(upload_to='messasge', height_field=None, width_field=None, blank=True, max_length=100, default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    cancel = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Notice(models.Model):
    kind_list=[
        (0,'system notice'),
        (1,'important or fatal notice in system notice'),
        (2,'notice from other users'),
    ]
    user = models.ForeignKey(CustomUser, related_name='notice', on_delete=models.CASCADE)
    kind = models.IntegerField(choices=kind_list,default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    text = models.TextField()


class Connect(models.Model):
    follow = models.ForeignKey(CustomUser, related_name='follow', on_delete=models.CASCADE)
    follower = models.ForeignKey(CustomUser, related_name='follower', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self): #admin上の表示設定
        display= str(self.follow) + " ⇒ " + str(self.follower)
        return display
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["follow", "follower"],name="connect_unique"),
        ]


class Block(models.Model):
    block = models.ForeignKey(CustomUser, related_name='block', on_delete=models.CASCADE)
    blocked = models.ForeignKey(CustomUser, related_name='blocked', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        display= str(self.block) + " ⇒ " + str(self.blocked)
        return display
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["block", "blocked"],name="block_unique"),
        ]

class Room(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='room', height_field=None, width_field=None, blank=True, max_length=100, default=False)#サムネ

    def __str__(self):
        return self.title
    
    def savePath(instance, filename):
        ext = filename.split('.')[-1]
        return f'room/{instance.id}.{ext}'
    


class Post(models.Model):
    text = models.TextField()
    user = models.ForeignKey(CustomUser, related_name='post', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(Room, related_name='post', on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    def __str__(self):
        return self.user.user_name + ' < ' + self.text + ' at ' +self.room.title
    
    image = models.ImageField(upload_to='post', height_field=None, width_field=None, blank=True, max_length=100, default=False)

chatrooms/views/system.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail, EmailMultiAlternatives
from .. import models, forms
from chatrooms.forms import LoginForm, CustomUserCreationForm
import datetime

from django.template.loader import get_template

class NoticeListView(LoginRequiredMixin, ListView):
    template_name = 'system/notice.html'
    model = models.Notice

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset()
        my_notice = queryset.filter(user=self.request.user).order_by('-created_at')[:20]
        my_notice_bin=[]
        for n in my_notice:
            my_notice_bin.append({
                'user': str(n.user),
                'kind': int(n.kind),
                'created_at': str(n.created_at).split('.')[0],
                'text': str(n.text)
            })
        queryset.filter(user=self.request.user).delete()
        return my_notice_bin

class NoticeDelete():
    pass

class ConfigView(LoginRequiredMixin, TemplateView):
    template_name = 'system/config.html'
    def get(self, request, **kwargs):
        ctx = {
            'user': self.request.user,
            'config': models.Config.objects.get(user=self.request.user),
            #'time': self.request.user.created_at-time.time()
            'form': forms.ConfigForm
        }
        return self.render_to_response(ctx)
    
    def post(self, request, **kwargs):
        config = models.Config.objects.get(user=self.request.user)

        print(request.POST['message'])
        print(request.POST['notice'])
        config.message = request.POST['message']
        config.notice = request.POST['notice']
        config.room_post_log = request.POST['room_post_log']
        config.friend = request.POST['friend']
        config.save()
        return redirect('cf')




class DevelopmentView(TemplateView):
    template_name = 'system/development.html'
    def get(self, request, **kwargs):
        self.meeru_okuru()

        return redirect('rl')

    def meeru_okuru(self):
        subject = 'メール送信テスト'
        message = 'やっほー'
        html_content = f"""
        <p>やほほー</p>
        """
        sent = 'aqurine117@gmail.com'
        receive = 'wakanohibiki0131@gmail.com'
        msg = EmailMultiAlternatives(
        subject, 
        message, 
        sent, 
        [receive])
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return 0

    """
    def get(self, request, **kwargs):
        for user in models.CustomUser.objects.all():
            print(user)
            models.Config.objects.create(
                user = user,
            )
        return redirect('rl')"""

class NavSearch(TemplateView):
    template_name = 'user/list.html'
    def get(self,request,**kwargs):
        inputed = request.GET['userid']
        context={}
        context['users_list']=models.CustomUser.objects.filter(username__contains=inputed)
        #return redirect('rl')
        return self.render_to_response(context)

templates/system/config.html
{% extends 'base.html' %}
{% block content %}
{% load config_default_set %}
<div class="container">
<div class="row">
    <form method="post" action="{% url 'cf' %}">
      <div class="col-6 border m-2 p-2">
        <p>ユーザー情報</p>
        <div>ID: {{user.username}}</div>
        <div>アカウント作成日: {{user.created_at|date:"Y/n/j"}}</div>
        <div>ルームコメント投稿総数: {{user.post.count}}</div>
      </div>
      {% csrf_token %}
      <div class="col-6 border m-2 p-2">
        <div class="py-2 m-2" name="message-config">{{form.message.label_tag}} {{user.config.get_message_display}}
          {%for f in form.message%}
          {%if f.data.value == user.config.message %}
          <div class="">{{f|config_default_set}}</div>
          {%else%}<div class="">{{f}} </div>
          {%endif%}
          {%endfor%}
        </div>
        <div class="py-2 m-2" name="notice-config">{{form.notice.label_tag}} {{user.config.get_notice_display}}
          {%for f in form.notice%}
          {%if f.data.value == user.config.notice %}
          <div class="">{{f|config_default_set}}</div>
          {%else%}<div class="">{{f}} </div>
          {%endif%}
          {%endfor%}
        </div>

      </div>
      <div class="col-6 border m-2 p-2">
        <div class="py-2 m-2" name="postlog-config">{{form.room_post_log.label_tag}} {{user.config.get_room_post_log_display}}
          {%for f in form.room_post_log%}
          {%if f.data.value == user.config.room_post_log %}
          <div class="">{{f|config_default_set}}</div>
          {%else%}<div class="">{{f}} </div>
          {%endif%}
          {%endfor%}
        </div>
        <div class="py-2 m-2" name="connect-config">{{form.friend.label_tag}} {{user.config.get_friend_display}}
          {%for f in form.friend%}
          {%if f.data.value == user.config.friend %}
          <div class="">{{f|config_default_set}}</div>
          {%else%}<div class="">{{f}} </div>
          {%endif%}
          {%endfor%}
        </div>
      </div>
      <button type="submit" class="btn btn-success my-2">更新する</button>
    </form>
  </div>
</div>
</div>
{% endblock %}

templates/system/notice.html
{% extends 'base.html' %}
{% load notice_kind_filter %}
{% block content%}
{% for object in object_list %}
{% if object.kind == 0 %}
<div class="m-2 p-2 bg-warning font-weight-bold">
{% elif object.kind == 1 %}
<div class="m-2 p-2 bg-danger font-weight-bold">
{% elif object.kind == 2 %}
<div class="m-2 p-2 bg-info">
{% endif %}
    <div>
        [{{object.created_at}} {{object.kind|notice_kind_filter}}]
    </div>
    {{object.text}}
</div>
{% endfor %}
{% endblock %}

templates/system/template.html
{%for object in object_list%}
{{object}}
{%endfor%}