chatrooms/urls.py
from django.urls import path, include
from .views import auth,system, user,connect,block,message,room

from django.contrib import admin

urlpatterns = [
    path('login', auth.Login.as_view(), name='li'),
    path('logout', auth.Logout.as_view(), name='lo'),

    path('config', system.ConfigView.as_view(), name='cf'),
    path('notice', system.NoticeListView.as_view(), name='nl'),



    path('user/list', user.UserListView.as_view(), name='ul'),
    path('user/search/<p>', user.UserSearchView.as_view(), name='us'),
    path('user/<int:pk>', user.UserDetailView.as_view(), name='ud'),
    path('user/create', user.UserCreateView.as_view(), name='uc'),
    path('user/<int:pk>/update', user.UserUpdateView.as_view(), name='uu'),
    path('user/<int:pk>/delete', user.UserDeleteView.as_view(), name='udl'),
    path('mypage', user.Mypage.as_view(), name='mp'),
    path('blocklist',block.BlockListView.as_view(), name='bl'),
    path('user/<int:pk>/block', block.BlockCreateView.as_view(), name='bc'),
    path('user/<int:pk>/blockend', block.BlockDeleteView.as_view(), name='bd'),
    path('user/<int:pk>/follow',connect.FollowListView.as_view(), name='fl1'),
    path('user/<int:pk>/follower',connect.FollowerListView.as_view(), name='fl2'),
    path('user/<int:pk>/connect',connect.ConnectCreateView.as_view(), name='cc'),
    path('user/<int:pk>/disconnect',connect.ConnectDeleteView.as_view(), name='cd'),
    path('messagebox',message.MessageBoxView.as_view(), name="mb"),
    path('message/<p>',message.MessageRoomView.as_view(), name="mr"),
    path('message/create/<p>',message.MessageCreate.as_view(), name="mc"),
    path('message/ajax',message.ajax, name="majax"),


    path('room/list', room.RoomListView.as_view(), name='rl'),
    path('room/<int:pk>/', room.RoomDetailView.as_view(), name='rd'),
    path('room/create', room.RoomCreateView.as_view(), name='rc'),
    path('room/<int:pk>/update', room.RoomUpdateView.as_view(), name='ru'),
    path('room/<int:pk>/delete', room.RoomDeleteView.as_view(), name='rdl'),

    path('room/<int:pk>/komento', room.PostCreate.as_view(), name='pc'),#ok

    path('dev', system.DevelopmentView.as_view(), name='dev'),
    path('dev/search', system.NavSearch.as_view(), name='ds'),
    path('', room.RoomListView.as_view(), name='index'),
]

chatroomsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('chatrooms.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chatrooms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    user_name = models.CharField(max_length=100, default="no name")
    memo = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    icon = models.ImageField(upload_to='icon', height_field=None, width_field=None, blank=True, max_length=100, default=False)
    icon_changed = models.DateTimeField(blank=True, auto_now=True)
    def __str__(self):
        return self.user_name
    
    REQUIRED_FIELDS = ["user_name","memo"]
    groups = None
    user_permissions = None
    last_login = None
    #superuser_status = False
    first_name = None
    last_name = None
    email_address = models.EmailField(default='notset@example.com')
    #staff_status = False
    date_joined = None

class Config(models.Model):
    open_config = [
        (0,'全体に公開する'),
        (1,'フレンドのみ公開'),
        (2,'非公開')
    ]
    receive_config = [
        (0,'全員に許可する'),
        (1,'フレンドのみ許可'),
        (2,'全員から受け取らない')
    ]

    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    darkmode = models.BooleanField(default=False,blank=False)
    room_post_log = models.IntegerField(choices=open_config, default=0)
    friend = models.IntegerField(choices=open_config, default=0)
    notice = models.IntegerField(choices=receive_config, default=0)
    message = models.IntegerField(choices=receive_config, default=0)

class Message(models.Model):
    sent = models.ForeignKey(CustomUser, related_name='sent_message', on_delete=models.CASCADE)
    received = models.ForeignKey(CustomUser, related_name='received_message', on_delete=models.CASCADE)
    text = models.TextField()
    image = models.ImageField(upload_to='messasge', height_field=None, width_field=None, blank=True, max_length=100, default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    cancel = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Notice(models.Model):
    kind_list=[
        (0,'system notice'),
        (1,'important or fatal notice in system notice'),
        (2,'notice from other users'),
    ]
    user = models.ForeignKey(CustomUser, related_name='notice', on_delete=models.CASCADE)
    kind = models.IntegerField(choices=kind_list,default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    text = models.TextField()


class Connect(models.Model):
    follow = models.ForeignKey(CustomUser, related_name='follow', on_delete=models.CASCADE)
    follower = models.ForeignKey(CustomUser, related_name='follower', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self): #admin上の表示設定
        display= str(self.follow) + " ⇒ " + str(self.follower)
        return display
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["follow", "follower"],name="connect_unique"),
        ]


class Block(models.Model):
    block = models.ForeignKey(CustomUser, related_name='block', on_delete=models.CASCADE)
    blocked = models.ForeignKey(CustomUser, related_name='blocked', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        display= str(self.block) + " ⇒ " + str(self.blocked)
        return display
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["block", "blocked"],name="block_unique"),
        ]

class Room(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='room', height_field=None, width_field=None, blank=True, max_length=100, default=False)#サムネ

    def __str__(self):
        return self.title
    
    def savePath(instance, filename):
        ext = filename.split('.')[-1]
        return f'room/{instance.id}.{ext}'
    


class Post(models.Model):
    text = models.TextField()
    user = models.ForeignKey(CustomUser, related_name='post', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(Room, related_name='post', on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    def __str__(self):
        return self.user.user_name + ' < ' + self.text + ' at ' +self.room.title
    
    image = models.ImageField(upload_to='post', height_field=None, width_field=None, blank=True, max_length=100, default=False)

chatrooms/views/connect.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, TemplateView
from .. import models
from django.contrib.auth.mixins import LoginRequiredMixin


class FollowListView(ListView):
    template_name = 'user/list.html'
    model = models.Connect
    context_object_name = "users_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['title'] = 'フォロー一覧'
        return context


    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs) 
        queryset = queryset.filter(follow_id=self.kwargs.get('pk')).order_by('-created_at')
        qs=[]
        for i in queryset:
            qs.append(i.follower)
        print(qs)
        return qs

class FollowerListView(ListView):
    template_name = 'user/list.html'
    model = models.Connect
    context_object_name = "users_list"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['title'] = 'フォロワー一覧'
        return context

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs) 
        queryset = queryset.filter(follower_id=self.kwargs.get('pk')).order_by('-created_at')
        qs=[]
        for i in queryset:
            qs.append(i.follow)
        print(qs)
        return qs

class ConnectCreateView(CreateView):
    template_name = 'user/connect.html'
    model = models.Connect
    fields = []
    def get_success_url(self):
          pk=self.kwargs['pk']
          return reverse_lazy('ud', kwargs={'pk': pk})
    def form_valid(self, form):
        form.instance.follow = self.request.user
        form.instance.follower = models.CustomUser.objects.get(id=self.kwargs.get('pk'))
        models.Notice.objects.update_or_create(
            user=models.CustomUser.objects.get(id=self.kwargs.get('pk')), 
            kind=2, 
            text=str(self.request.user)+' has follow you!'
            )
        return super(ConnectCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context=super().get_context_data() #元クラスで定義されてるデフォルトのcontextを呼び出してます
        extra={
            'target': models.CustomUser.objects.get(id=self.kwargs.get('pk')),
            'f_or_b': 'フォロー'
        }
        context.update(extra)
        return context
    

class ConnectDeleteView(DeleteView):
    template_name = 'user/connectdel.html'
    model = models.Connect
    
    def post(self,request,**kwargs):
        try:
            connect = models.Connect.objects.get(follower_id=self.kwargs.get('pk'),follow_id=self.request.user.id)
            connect.delete()
        except:
            pass
        return redirect('ul')


    def get_context_data(self, **kwargs):
        context=super().get_context_data() #元クラスで定義されてるデフォルトのcontextを呼び出してます
        extra={
            'target': models.CustomUser.objects.get(id=self.kwargs.get('pk')),
            'f_or_b': 'フォロー'
            }
        context.update(extra)
        return context

    def get_object(self, queryset=None):
        connect = models.Connect.objects.get(follower_id=self.kwargs.get('pk'),follow_id=self.request.user.id)
        return connect

chatrooms/views/user.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .. import models
from ..forms import CustomUserCreationForm, CustomUserSearchForm
from . import mixins
from django.contrib.auth.mixins import LoginRequiredMixin
from PIL import Image

class UserCreateView(CreateView):
    template_name = 'user/create.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('rl')

class UserListView(ListView):
    template_name = 'user/list.html'
    model = models.CustomUser
    context_object_name = "users_list"
    def get_queryset(self, **kwargs):
        qs=super().get_queryset(**kwargs)
        for u in qs:
            try:
                models.Block.objects.get(block_id=self.request.user.pk, blocked_id=u.pk)
                print('I blocked '+str(u.username))
                qs = qs.exclude(id=u.pk)
            except:
                pass
            try:
                models.Block.objects.get(blocked_id=self.request.user.pk, block_id=u.pk)
                print(str(u.username)+' blocked me')
                qs = qs.exclude(id=u.pk)
            except:
                pass
        return qs



    def get_context_data(self, **kwargs):
        context=super().get_context_data()
        return context

class UserSearchView(ListView):
    template_name = 'user/list.html'
    model = models.CustomUser
    context_object_name = "users_list"
    def get_context_data(self, **kwargs):
        context=super().get_context_data()
        context['users_list'] = models.CustomUser.objects.filter(username__contains=self.kwargs.get('p'))
        return context

def usersearch(request):
    searchForm = CustomUserSearchForm(request.GET)
    # searchForm変数に正常なデータがあれば
    if searchForm.is_valid():
        username = searchForm.cleaned_data['username'] # keyword変数にフォームのキーワードを代入
        users = models.CustomUser.objects.filter(username=username) # キーワードを含むレコードをfilterメソッドで取り出し、articles変数に代入
    # それ以外の場合
    else:
        searchForm = CustomUserSearchForm() # searchForm変数をSearchFormオブジェクトで上書き
        users = models.CustomUser.objects.all() # すべてのレコードを取得
 
    context = {
    'users_list': users,
    'searchForm': searchForm, # テンプレートに渡すために追記
    }
    return render(request, 'user/list.html', context)

class UserDetailView(LoginRequiredMixin, mixins.BlockTestMixin, DetailView):
    template_name = 'user/detail.html'
    model = models.CustomUser
    def get(self, request, **kwargs):
        if self.request.user.id == self.kwargs.get('pk'):
            return redirect('mp')
        else:
            return super().get(request)

    def get_context_data(self, **kwargs):
        context=super().get_context_data() #元クラスで定義されてるデフォルトのcontextを呼び出してます
        try: 
            models.Connect.objects.get(follower_id=self.kwargs.get('pk'),follow_id=self.request.user.id)
            context['follow_flag'] = True
        except:
            context['follow_flag'] = False
        try: 
            models.Block.objects.get(blocked_id=self.kwargs.get('pk'),block_id=self.request.user.id)
            context['block_flag'] = True
        except:
            context['block_flag'] = False
        try: 
            imgurl=models.CustomUser.objects.get(id=self.kwargs.get('pk')).icon
            if imgurl=='False':
                imgurl="icon/none.png"
            context['imgurl'] = "/media/" + str(imgurl)
        except:
            context['imgurl'] = "/media/icon/none.png"
        return context



class UserUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'user/update.html'
    model = models.CustomUser
    fields = ['user_name', 'memo', 'icon']
    success_url = reverse_lazy('mp')

    def get_context_data(self, **kwargs):
       context=super().get_context_data()
       print(context)
       return context

class UserDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'user/delete.html'
    model = models.CustomUser
    success_url = reverse_lazy('ul')

class Mypage(LoginRequiredMixin, TemplateView):
    template_name = 'user/mypage.html'
    def get(self, request, **kwargs):
        try: 
            imgurl = self.request.user.icon
            if imgurl=='False':
                imgurl='/media/icon/none.png'
            else:
                imgurl = "/media/" + str(imgurl) 
        except:
            imgurl = "/media/icon/none.png"
        ctx = {
            'user': self.request.user,
            'imgurl' : imgurl
        }
        if self.request.user.icon != 'False':
            img = Image.open("media_local/"+str(self.request.user.icon))
            if img.width!=256 or img.height!=256:
                img_resize = img.resize((256, 256))
                img_resize.save("media_local/"+str(self.request.user.icon))
        return self.render_to_response(ctx)

    def get_context_data(self, **kwargs):
        context=super().get_context_data() #元クラスで定義されてるデフォルトのcontextを呼び出してます
        try: 
            imgurl = models.Connect.objects.get(follower_id=self.kwargs.get('pk'),follow_id=self.request.user.id)
            context['iconurl'] = "/media/" + str(imgurl) 
        except:
            context['iconurl'] = False
        return context

templates/user/connect.html
{% extends 'base.html' %}
{% block content %}
  <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <p class="m-2">{{target}}を{{f_or_b}}しますか？</p>
    {{ form.as_p }}
    <button type="submit" class="btn {%if f_or_b == 'フォロー' %}btn-primary{%else%}btn-danger{%endif%} mt-4">{{f_or_b}}する</button>
  </form>
</body>

{% endblock %}

templates/user/connectdel.html
{% extends 'base.html' %}
{% block content %}
  <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <p class="m-2">{{target}}の{{f_or_b}}を解除しますか？</p>
    {{ form.as_p }}
    <button type="submit" class="btn {%if f_or_b == 'フォロー' %}btn-primary{%else%}btn-danger{%endif%} mt-4">{{f_or_b}}を解除する</button>
  </form>
</body>
{% endblock %}

templates/user/create.html
{% extends 'base.html' %}
{% block content %}
  <form method="post" enctype="multipart/form-data class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success mt-4">登録</button>
  </form>
</body>

{% endblock %}

templates/user/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">

      <div class="row justify-content-md-center pt-4">
        <img src={{imgurl}} alt={{customuser.icon}} class="col-auto rounded-circle" width="100" height="100">
      </div>
      <div class="pt-4" name="name">
        <h4 class="text-center">{{ customuser.user_name }}</h4>
        <p class="text-center">@{{ customuser.username }}</p>

        <div class="row justify-content-md-center" name="ff">
          <div class="col-auto row justify-content-md-center" name="follow">
            <a href={%url 'fl1' customuser.id%} class="btn col-auto text-center text-decoration-none">フォロー</a>
            <div class="col-12"></div>
            <a href={%url 'fl1' customuser.id%} class="btn col-auto text-center text-decoration-none">{{ customuser.follow.count}}</a>
          </div>
          <div class="col-auto row justify-content-md-center" name="follower">
            <a href={%url 'fl2' customuser.id%} class="btn col-auto text-center text-decoration-none">フォロワー</a>
            <div class="col-12"></div>
            <a href={%url 'fl2' customuser.id%} class="btn col-auto text-center text-decoration-none">{{ customuser.follower.count}}</a>
          </div>
        </div>

        <div class="row p-4 justify-content-md-center">
          {%if not block_flag%}
          {%if not follow_flag%}
          <a href={%url 'cc' customuser.id%} class="btn btn-primary col-auto">フォロー</a>
          {%else%}
          <a href={%url 'cd' customuser.id%} class="btn btn-secondary col-auto">フォロー解除</a>
          {%endif%}
          {%endif%}
          <a href={%url 'mr' customuser.username%} class="btn btn-white col-auto border border3 ms-2">メッセージ</a>
        </div>
        <div class="row p-2 justify-content-md-center">
          {%if not block_flag%}
          <a href={%url 'bc' customuser.pk%} class="btn btn-danger col-auto">ブロック</a>
          {%else%}
          <a href={%url 'bd' customuser.pk%} class="btn btn-secondary col-auto">ブロック解除</a>
          {%endif%}
        </div>
      </div>
    </div>

    <div class="container  mt-4">
      <p class="mt-2">投稿履歴{% if customuser.post.count == 0 %}なし{%endif%}</p>
      {% for post in customuser.post.all %}
      <div class=" rounded container p-2 m-2 bg-light">
        <a href={%url 'rd' post.room.id%} class="text-dark text-decoration-none">
          <p>{{ post.text }}</p>
          {{ post.created_at|date:"Y/n/j H:i"}}
          {{ post.room }}
        </a>
      </div>
      {% endfor %}
    </div>



{% endblock content %}

{%block css%}
{%endblock css%}

templates/user/follow.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-hover">
        <thead>
            <tr>
              <th scope="col">FROM</th>
              <th scope="col">TO</th>
            </tr>
          </thead>
          <tbody>
            {% for connect in connect_list %}
            <tr>
              <td><a href={% url 'ud' connect.follow.id %} class="text-dark text-decoration-none"} >@{{ connect.follow.username }}</a></td>
              <td><a href={% url 'ud' connect.follower.id %} class="text-dark text-decoration-none"}>{{ connect.follower.username }}</a></td>
            </tr>
            {% endfor %}
          </tbody>
    </table>
    <a href={%url 'uc'%} class="btn btn-primary m-4">ユーザー作成</a>
{% endblock content %}

templates/user/list.html
{% extends 'base.html' %}
{% load icon_filter %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
{{search}}
<div class="container">
  <div class="row justify-content-md-center">
  {%for user_ in users_list%}
  <div class="col-9 p-2 mt-2 row border-bottom" name="user">
    <div class="col-auto" name="icon">
      <img src={{user_.icon|icon_filter}} alt={{user_.icon}} class="rounded-circle col-auto" width="64" height="64">
    </div>
    <div class="col-auto" name="name+id-and-memo">
      <div class="" name="name+id"><a href={%url 'ud' user_.pk%} class="text-decoration-none text-dark">{{user_}} @{{user_.username}}</a></div>
      <div class="" name="memo">{{user_.memo|linebreaksbr}}</div>
    </div>
  </div>
  {%endfor%}
</div>
</div>
{% endblock content %}

templates/user/login.html
{% extends 'base.html' %}
{% block content %}
<p>ログインしてください</p>
<form method="post" action="{% url 'li' %}" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <td><label for="userid">ユーザーID: </label></td>
    <td><input type="text" name="username"></td>
    <div class="my-2"></div>
    <td><label for="password">パスワード: </label></td>
    <td><input type="password" name="password"></td>
    <div></div>
    <input type="submit" class="btn btn-primary mt-2" value="ログイン">
 </form>
 <a href={%url 'uc'%} class="mx-2 btn btn-secondary">アカウント作成</a>
{% endblock content %}

templates/user/mypage.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
      <div class="row justify-content-md-center pt-4">
        <img src={{imgurl}} alt={{user.icon}} class="col-auto rounded-circle" width="100" height="100">
      </div>
      <div class="pt-4" name="name">
        <h4 class="text-center">{{ user.user_name }}</h4>
        <p class="text-center">@{{ user.username }}</p>

        <div class="row justify-content-md-center p-4" name="ff">
          <div class="col-auto row justify-content-md-center" name="follow">
            <a href={%url 'fl1' user.id%} class="btn col-auto text-center text-decoration-none">フォロー</a>
            <div class="col-12"></div>
            <a href={%url 'fl1' user.id%} class="btn col-auto text-center text-decoration-none">{{ user.follow.count}}</a>
          </div>
          <div class="col-auto row justify-content-md-center" name="follower">
            <a href={%url 'fl2' user.id%} class="btn col-auto text-center text-decoration-none">フォロワー</a>
            <div class="col-12"></div>
            <a href={%url 'fl2' user.id%} class="btn col-auto text-center text-decoration-none">{{ user.follower.count}}</a>
          </div>
        </div>
        <div class="text-center">
          <a href={%url 'uu' user.id%} class="text-center btn btn-success">プロフィール設定</a>
          <a href={%url 'bl'%} class="text-center btn btn-danger">ブロック一覧</a>
          <a href={%url 'mb'%} class="text-center btn btn-primary">メッセージ
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-mailbox2" viewBox="0 0 16 16">
            <path d="M9 8.5h2.793l.853.854A.5.5 0 0 0 13 9.5h1a.5.5 0 0 0 .5-.5V8a.5.5 0 0 0-.5-.5H9v1z"/>
            <path d="M12 3H4a4 4 0 0 0-4 4v6a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V7a4 4 0 0 0-4-4zM8 7a3.99 3.99 0 0 0-1.354-3H12a3 3 0 0 1 3 3v6H8V7zm-3.415.157C4.42 7.087 4.218 7 4 7c-.218 0-.42.086-.585.157C3.164 7.264 3 7.334 3 7a1 1 0 0 1 2 0c0 .334-.164.264-.415.157z"/>
            </svg>
          </a>
        </div>
      </div>
    </div>

    <div class="container  mt-4">
      <p class="mt-2">投稿履歴{% if user.post.count == 0 %}なし{%endif%}</p>
      {% for post in user.post.all %}
      <div class=" rounded container p-2 m-2 bg-light">
        <a href={%url 'rd' post.room.id%} class="text-dark text-decoration-none">
          <p>{{ post.text }}</p>
          {{ post.created_at|date:"Y/n/j H:i"}}
          {{ post.room }}
        </a>
      </div>
      {% endfor %}
    </div>



{% endblock content %}

templates/user/update.html
{% extends 'base.html' %}
{% block content %}
  <form method="post" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success mt-4">登録</button>
  </form>
</body>

{% endblock %}